name = "Build"

[build]
command = "./build.sh"
publish_dir = "public"

[build.environment]
HUGO_VERSION = "0.143.1"
HUGO_ENV = "production"

[build.upload]
exclude = [
  "node_modules",
  ".git",
  ".gitignore",
  "README.md",
]

[build.preview]
command = "hugo --minify --baseURL $CF_PAGES_URL"
